version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 16.x
    pre_build:
        commands:
            - echo Installing NPM dependencies
            - npm ci --legacy-peer-deps
    build:
        commands:
            - echo Build started on `date`
            - npm run build
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        # - /**/*
        - build/**/*
        - appspec.yml
        - scripts/*
cache:
    paths:
        - node_modules
